name: First Grid Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2652533680666238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9164821084123105
  lightness: 0.7921837489120662
  saturation: 0.6746579753234982
  rhythmicContrast: 0.75
purpose: []
